version: 2

models:
  - name: Airline
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: int64
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: string
      - name: alias
        data_type: string
      - name: iata
        data_type: string
      - name: icao
        data_type: string
      - name: callsign
        data_type: string
      - name: country
        data_type: string
        constraints:
          - type: foreign_key
            to: dbt_air_travel_int.Country
            to_columns: [name]
        tests:
          - relationships:
              to: ref('Country')
              field: name
      - name: active
        data_type: boolean
