version: 2

models:
  - name: TSA_Traffic
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [event_date, event_hour, airport_icao, tsa_checkpoint]
    columns:
      - name: event_date
        data_type: date
        tests:
          - not_null
      - name: event_hour
        data_type: int64
        tests:
          - not_null
      - name: airport_icao
        data_type: string
        constraints:
          - type: foreign_key
            to: dbt_air_travel_int.Airport
            to_columns: [icao]
        tests:
          - not_null
      - name: tsa_checkpoint
        data_type: string
      - name: passenger_count
        data_type: int64
        tests:
          - not_null
    tests:
      - unique_combination_of_columns: 
          combination_of_columns:
            - event_date
            - event_hour
            - airport_icao
            - tsa_checkpoint
