version: 2

models:
  - name: Country
    config:
      contract:
        enforced: true
    columns:
      - name: name
        data_type: string
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: iso_code
        data_type: string
      - name: dafif_codes
        data_type: array<string>